### ISSUE TITLE
Install MySql 5.6.17 on RPi

### ISSUE THREAD

**Issue by zacarius89** [zacarius89/KewlKidsFitIn#11]
Install the same version of MySQL that wamp is using on the Raspberry Pi.
It will make database restores actually possible.

**Comment by DanielCoffaro** [comment]
I have looked into this, and am wondering if its not possible. :/ Still researching

**Comment by zacarius89** [comment]
This is done.
I moved the database to RDS in AWS.  And it is the latest version of mysql.
